#server:
#  port: 7080
#
#
##在这里我没有写driver-class-name: com.mysql.jdbc.Driver这个驱动被弃用了  使用新版com.mysql.cj.jdbc.Driver
##控制台提示说自动帮我们找相应的驱动，一般无需手动加载，所以我注释掉了
#spring:
#  application:
#    name: employee-manage
#  cloud:
#    client:
#      ip-address: 127.0.0.1
#  main:
#    allow-bean-definition-overriding: true
#  http:
#    encoding:
#      enabled: true
#      charset: UTF-8
#      force: true
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    # 初始化Druid
#    druid:
#      # mysql数据库接地址jdbc:mysql://192.168.43.114:3306/boot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
#      url: jdbc:mysql://127.0.0.1:3306/boot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: 123456
#      initialSize: 5
#      minIdle: 5
#      maxActive: 20
#      #security的配置信息
#  security:
#    loginType: json
##redis的配置信息
#  redis:
#    host: 127.0.0.1
#    timeout: 3000
#    password:
#    port: 6379
#    database: 0
#    jedis:
#      pool:
#        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 8   # 连接池中的最大空闲连接
#        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制)
#        min-idle: 0
#
##mybatis-plus的配置信息
#mybatis-plus:
#  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
#  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
#  mapper-locations: classpath*:com/rrk/common/modules/manage/mapper/*.xml
#  type-aliases-package: com.rrk.common.modules.manage.entity
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 2
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 1
#    #驼峰下划线转换
#    db-column-underline: true
#    #mp2.3+ 全局表前缀 mp_
#    #table-prefix: mp_
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #逻辑删除配置（下面3个配置）
#    logic-delete-value: 1
#    logic-not-delete-value: 0
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: true
##忽略需要认证才能访问的url
#ignored:
#  urls:
#    - /login
#    - /upload/addImage
#    - /product/addKillProduct
#    - /product/getKillProduct
#    - /product/getKillProductList
#    - /product/getKillProductDetail
#    - /manage/login
#    - /manage/userInfo
#    - /manage/getPermissionsByUser
#    - /product/getProductList
#    - /user/getSmsCode
#    - /user/smsLogin
#    - /upload/addImage
#    - /product/addProduct
#
##安全认证
#dinghao:
#  auth:
#    # token过期时间（秒钟）
#    tokenExpireTime: 1800
#    # 用户选择保存登录状态对应token过期时间（天）
#    saveLoginTime: 7
#    # 限制用户登陆错误次数（次）
#    loginTimeLimit: 10
#    # 错误超过次数后多少分钟后才能继续登录（分钟）
#    loginAfterTime: 10
#
#
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://gogs.com:9099/eureka/,http://192.168.43.9:9098/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
#
#management:
#  endpoints:
#    web:
#      eposure:
#        include: env ,health ,refresh, info
#
#feign:
#  hystrix:
#    enabled: true #feign开启hystrix支持
#  compression:
#    request:
#      enabled: true
#      mime-types: text/xml,application/xml,application/json # 配置压缩支持的MIME
#      min-request-size: 2048  # 配置压缩数据大小的下限
#    response:
#      enabled: true # 配置响应GZIP压缩